# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: üè≠‰∫¨Âñú-Ê¢¶Â∑•ÂéÇ

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' 
  watch:
    types: started
  repository_dispatch:
    types: dreamFactory
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
          #repository: lxk0301/scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # ‰ΩøÁî® GitHub ÂÆòÊñπÁöÑÁºìÂ≠ò Action„ÄÇ
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # ‰ΩøÁî® package-lock.json ÁöÑ Hash ‰Ωú‰∏∫ÁºìÂ≠òÁöÑ key„ÄÇ‰πüÂèØ‰ª•‰ΩøÁî® package.json ‰ª£Êõø
      - name: npm install
        run: |
          npm install
      - name: 'ËøêË°å „Äê‰∫¨Âñú-Ê¢¶Â∑•ÂéÇ„Äë'
        run: |
          node jd_dreamFactory.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE_JXGC }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}
